<template>
  <g>
    <!-- 港島 Hong Kong Island -->
    <circle
      data-pin="eastern"
      cx="628"
      cy="636"
      r="6"
    />
    <!-- 九龍 Kowloon -->
    <circle
      data-pin="sham-shui-po"
      cx="517"
      cy="544"
      r="6"
    />
    <circle
      data-pin="yau-tsim-mong"
      cx="537"
      cy="580"
      r="6"
    />
    <circle
      data-pin="yau-tsim-mong"
      cx="549"
      cy="586"
      r="6"
    />
    <circle
      data-pin="wong-tai-sin"
      cx="596"
      cy="522"
      r="6"
    />
    <circle
      data-pin="kwun-tong"
      cx="639"
      cy="583"
      r="6"
    />
    <!-- 新界 New Territories -->
    <circle
      data-pin="kwai-tsing"
      cx="467"
      cy="521"
      r="6"
    />
    <circle
      data-pin="tuen-mun"
      cx="224"
      cy="470"
      r="6"
    />
    <circle
      data-pin="yuen-long"
      cx="327"
      cy="335"
      r="6"
    />
    <circle
      data-pin="yuen-long"
      cx="339"
      cy="327"
      r="6"
    />
    <circle
      data-pin="north"
      cx="673"
      cy="226"
      r="6"
    />
    <circle
      data-pin="sha-tin"
      cx="602"
      cy="436"
      r="6"
    />
    <!-- 離島 Islands -->
    <circle
      data-pin="islands"
      cx="340"
      cy="680"
      r="6"
    />
  </g>
</template>
