export const BOOK_CATEGORIES = [
  { i18nKey: 'book_category.antiques_collectibles', value: 'Antiques & Collectibles' },
  { i18nKey: 'book_category.architecture', value: 'Architecture' },
  { i18nKey: 'book_category.art', value: 'Art' },
  { i18nKey: 'book_category.bibles', value: 'Bibles' },
  { i18nKey: 'book_category.biography_autobiography', value: 'Biography & Autobiography' },
  { i18nKey: 'book_category.business_economics', value: 'Business & Economics' },
  { i18nKey: 'book_category.comics_graphic_novels', value: 'Comics & Graphic Novels' },
  { i18nKey: 'book_category.computers', value: 'Computers' },
  { i18nKey: 'book_category.cooking', value: 'Cooking' },
  { i18nKey: 'book_category.crafts_hobbies', value: 'Crafts & Hobbies' },
  { i18nKey: 'book_category.design', value: 'Design' },
  { i18nKey: 'book_category.drama', value: 'Drama' },
  { i18nKey: 'book_category.education', value: 'Education' },
  { i18nKey: 'book_category.family_relationships', value: 'Family & Relationships' },
  { i18nKey: 'book_category.fiction', value: 'Fiction' },
  { i18nKey: 'book_category.games_activities', value: 'Games & Activities' },
  { i18nKey: 'book_category.gardening', value: 'Gardening' },
  { i18nKey: 'book_category.health_fitness', value: 'Health & Fitness' },
  { i18nKey: 'book_category.history', value: 'History' },
  { i18nKey: 'book_category.house_home', value: 'House & Home' },
  { i18nKey: 'book_category.humor', value: 'Humor' },
  { i18nKey: 'book_category.juvenile_fiction', value: 'Juvenile Fiction' },
  { i18nKey: 'book_category.juvenile_nonfiction', value: 'Juvenile Nonfiction' },
  { i18nKey: 'book_category.language_arts_disciplines', value: 'Language Arts & Disciplines' },
  { i18nKey: 'book_category.language_study', value: 'Language Study' },
  { i18nKey: 'book_category.law', value: 'Law' },
  { i18nKey: 'book_category.literary_collections', value: 'Literary Collections' },
  { i18nKey: 'book_category.literary_criticism', value: 'Literary Criticism' },
  { i18nKey: 'book_category.mathematics', value: 'Mathematics' },
  { i18nKey: 'book_category.medical', value: 'Medical' },
  { i18nKey: 'book_category.mind_body_spirit', value: 'Mind, Body, Spirit' },
  { i18nKey: 'book_category.music', value: 'Music' },
  { i18nKey: 'book_category.nature', value: 'Nature' },
  { i18nKey: 'book_category.performing_arts', value: 'Performing Arts' },
  { i18nKey: 'book_category.pets', value: 'Pets' },
  { i18nKey: 'book_category.philosophy', value: 'Philosophy' },
  { i18nKey: 'book_category.photography', value: 'Photography' },
  { i18nKey: 'book_category.poetry', value: 'Poetry' },
  { i18nKey: 'book_category.political_science', value: 'Political Science' },
  { i18nKey: 'book_category.psychology', value: 'Psychology' },
  { i18nKey: 'book_category.reference', value: 'Reference' },
  { i18nKey: 'book_category.religion', value: 'Religion' },
  { i18nKey: 'book_category.science', value: 'Science' },
  { i18nKey: 'book_category.self_help', value: 'Self-Help' },
  { i18nKey: 'book_category.social_science', value: 'Social Science' },
  { i18nKey: 'book_category.sports_recreation', value: 'Sports & Recreation' },
  { i18nKey: 'book_category.study_aids', value: 'Study Aids' },
  { i18nKey: 'book_category.technology_engineering', value: 'Technology & Engineering' },
  { i18nKey: 'book_category.transportation', value: 'Transportation' },
  { i18nKey: 'book_category.travel', value: 'Travel' },
  { i18nKey: 'book_category.true_crime', value: 'True Crime' },
  { i18nKey: 'book_category.young_adult_fiction', value: 'Young Adult Fiction' },
  { i18nKey: 'book_category.young_adult_nonfiction', value: 'Young Adult Nonfiction' },
] as const

const GENRE_TO_I18N_MAP = new Map<string, string>(
  BOOK_CATEGORIES.map(category => [category.value, category.i18nKey]),
)

export function getGenreI18nKey(genre: string): string | undefined {
  return GENRE_TO_I18N_MAP.get(genre)
}
