export const featuredLocalHistories = [
  {
    title: '小村長',
    region: '北部',
    isPublished: false,
    summary: '深耕三峽在地，透過採編挖掘社區裡的人情味與職人故事。',
    tags: ['社區', '職人'],
  },
  {
    title: '今秋誌',
    region: '中部',
    isPublished: false,
    summary: '配合鹿港今秋藝術節出版，探討古鎮文化資產與現代藝術的結合。',
    tags: ['藝術', '文資'],
  },
  {
    title: '貢丸湯',
    region: '北部',
    isPublished: false,
    summary: '以新竹為基地，挖掘城市空間、產業記憶與當代市民生活。',
    tags: ['都市設計', '生活'],
  },
  {
    title: '新莊騷',
    region: '北部',
    isPublished: true,
    summary: '記錄新莊從百年老街到現代副都心的文化脈動與庶民記憶。',
    tags: ['歷史', '生活'],
  },
  {
    title: '臺東土黏黏',
    region: '東部',
    isPublished: true,
    summary: '記錄台東這塊「黏人」土地上的移居者、自然農法與緩慢生活。',
    tags: ['台東', '土地'],
  },
  {
    title: '南瀛文化協會',
    region: '南部',
    isPublished: true,
    summary: '關注成人學習、文化資產、社區營造、宜居城鄉、食農教育、水資源、閱讀推廣、在地旅行導覽、歷史空間保存活化、地方創生等議題。',
    tags: ['文化', '社區營造'],
  },
  {
    title: '書粥工作室',
    region: '南部',
    isPublished: true,
    summary: '書粥位於台東長濱，是一間以「打工換宿」徵求來自各地的人擔任店長的書店,疫情期間成立了一人出版社。',
    tags: ['文化', '社區營造'],
  },
  {
    title: '深溝年報',
    region: '東部',
    isPublished: false,
    summary: '記錄宜蘭深溝新農社群的半農半 X 生活，探討當代農業與土地議題。',
    tags: ['農業', '新生活'],
  },
  {
    title: 'WindAndBones',
    region: '南部',
    isPublished: true,
    summary: '由 Hannah Stevens 與 Will Buckingham 創立的獨立出版社，致力於透過故事書寫、跨文化對話與社群參與推動社會變革。',
    tags: ['文化', '社會變革'],
  },
  {
    title: '科學月刊',
    region: '北部',
    isPublished: true,
    summary: '創刊於1970年1月1日，以專業、正確的觀點介紹科學新知與評論。',
    tags: ['自然科學', '公共知識'],
  },
  {
    title: '台灣獨立書店文化協會',
    region: '中部',
    isPublished: true,
    summary: '它是由台灣一群獨立書店經營者以及獨立書店的讀者們，為記錄和發展獨立書店特有的文化與精神、共同為社會改革而努力。',
    tags: ['社會改革', '文化'],
  },
  {
    title: '屏東本事',
    region: '南部',
    isPublished: false,
    summary: '屏東文化局出版，精選屏東在地傑出藝文、地景與人文故事。',
    tags: ['文化', '藝文'],
  },
  {
    title: '浪金山',
    region: '北部',
    isPublished: true,
    summary: '是一群年輕人組成的地方創生團隊，自2022年駐點新北金山，致力於透過Podcast《浪集》記錄在地故事，並營造「浪聚」交流空間與「浪居」換宿服務，整合餐飲、藝術與在地文化，打造具有「先安居，再樂業」理念的生活文化平台。',
    tags: ['文化', '社區營造'],
  },
  {
    title: 'Amazing Pingtung 驚艷屏東',
    region: '南部',
    isPublished: false,
    summary: '透過鮮活視覺呈現屏東的自然美景、節慶活動與多元族群色彩。',
    tags: ['旅遊', '地景'],
  },
  {
    title: 'FOUNTAIN 新活水',
    region: '全台',
    isPublished: false,
    summary: '跨領域的文化刊物，透過深度專題挖掘台灣當代文化趨勢與歷史思維。',
    tags: ['文化', '議題'],
  },
  {
    title: '台毒誌',
    region: '全台',
    isPublished: false,
    summary: '帶有強烈風格的獨立刊物，探討台灣在地文化與社會意識。',
    tags: ['社會', '文化'],
  },
  {
    title: '小日子享生活誌',
    region: '全台',
    isPublished: false,
    summary: '以簡潔美學風格報導台灣各角落的小人物日常與質感生活。',
    tags: ['美學', '生活'],
  },
  {
    title: '台灣食通信系列',
    region: '全台',
    isPublished: false,
    summary: '隨刊附贈食材的實驗性刊物，連結生產者與消費者，講述土地與食物的故事。',
    tags: ['食育', '農業'],
  },
  {
    title: '海想知道',
    region: '北部',
    isPublished: false,
    summary: '基隆在地團隊製作，從漁港、海鮮到海民生活，探索基隆的海洋屬性。',
    tags: ['海洋', '基隆'],
  },
  {
    title: '地味手帖',
    region: '全台',
    isPublished: false,
    summary: '以主題方式探討台灣各地的移居生活、社區營造與地方創生。',
    tags: ['地方創生', '移居'],
  },
  {
    title: '炯話郎',
    region: '中部',
    isPublished: false,
    summary: '彰化青年返鄉採編，記錄老街轉型、獨立書店與彰化人的日常點滴。',
    tags: ['青年返鄉', '彰化'],
  },
  {
    title: '山海集',
    region: '中部',
    isPublished: false,
    summary: '苗栗在地刊物，挖掘山城與海線之間的產業歷史與自然地景。',
    tags: ['地理', '山城'],
  },
  {
    title: '龜山不是島',
    region: '北部',
    isPublished: false,
    summary: '記錄桃園龜山的眷村史、工業發展及在地居民的生活變遷。',
    tags: ['眷村', '歷史'],
  },
  {
    title: '五花鹽',
    region: '全台',
    isPublished: false,
    summary: '以強烈的立場與史觀，重新解構台灣歷史、政治與語言。',
    tags: ['歷史', '政治'],
  },
  {
    title: '台味誌',
    region: '全台',
    isPublished: false,
    summary: '以趣味、深入淺出的方式，定義與推廣台灣飲食與生活中的「台味」。',
    tags: ['飲食', '台味'],
  },
  {
    title: '雞籠霧雨',
    region: '北部',
    isPublished: false,
    summary: '透過批判性視角觀察基隆都市空間、文資保存與底層社會。',
    tags: ['都市考現', '文資'],
  },
  {
    title: '淡淡',
    region: '北部',
    isPublished: false,
    summary: '淡水在地刊物，捕捉淡水河畔的小城故事、古蹟保存與文化觀光。',
    tags: ['淡水', '文化'],
  },
  {
    title: '東園誌',
    region: '北部',
    isPublished: false,
    summary: '聚焦台北萬華東園街一帶，記錄老社區的職人、市場與生活轉型。',
    tags: ['萬華', '老街區'],
  },
  {
    title: '掀海風',
    region: '中部',
    isPublished: false,
    summary: '苗栗苑裡返鄉團隊創辦，記錄稻作文化、藺草工藝與家鄉轉變。',
    tags: ['藺草', '文化'],
  },
  {
    title: '員林紀事',
    region: '中部',
    isPublished: false,
    summary: '挖掘員林的產業根基、傳統小吃與在地家族的生命史。',
    tags: ['員林', '家族'],
  },
  {
    title: '慢漫刊',
    region: '南部',
    isPublished: false,
    summary: '捕捉嘉義緩慢的生活步調，記錄木都文化、老屋新生與市井日常。',
    tags: ['嘉義', '老屋'],
  },
  {
    title: '大雄誌',
    region: '南部',
    isPublished: false,
    summary: '高雄在地文化誌，從工業城市轉型的角度，記錄高雄的街道與人物。',
    tags: ['高雄', '港都'],
  },
  {
    title: '臺東土黏黏',
    region: '東部',
    isPublished: false,
    summary: '記錄台東這塊「黏人」土地上的移居者、自然農法與緩慢生活。',
    tags: ['台東', '土地'],
  },
  {
    title: 'parking',
    region: '南部',
    isPublished: true,
    summary: '由旅居台南的日本攝影師名倉慶佑與在地友人吳易軒創辦。以「Tainan-sense」為核心，透過咖啡師與攝影師的獨特感官，採訪台南百工百業，記錄在地人與移居者在這座城市「停下來」的點滴。',
    tags: ['移居者', '攝影', '職人'],
  },
  {
    title: '透南風',
    region: '南部',
    isPublished: false,
    summary: '深入南台灣土地，記錄傳統職人、農業與民間工藝的勞動精神。',
    tags: ['職人', '工藝'],
  },
  {
    title: '鑛山誌',
    region: '北部',
    isPublished: false,
    summary: '記錄金瓜石、九份一帶的鑛業歷史、山城聚落與居民生活。',
    tags: ['鑛業', '山城'],
  },
  {
    title: '大角誌',
    region: '離島',
    isPublished: false,
    summary: '澎湖地方採編刊物，挖掘菊島在地的自然生態與常民生活。',
    tags: ['澎湖', '自然'],
  },
  {
    title: '小鰆誌',
    region: '離島',
    isPublished: false,
    summary: '聚焦澎湖海洋文化與飲食，記錄這座海島隨季節更迭的生命力。',
    tags: ['海洋', '飲食'],
  },
  {
    title: '寫寫字採編學堂',
    region: '東部',
    isPublished: true,
    summary: '由資深採編人王玉萍發起，以花蓮為基地。透過開辦課程，帶領學員走進新社、港口等聚落進行深度採訪，記錄職人工藝、土地變遷與移居者故事。',
    tags: ['地方創生', '職人'],
  },
]
